CREATE DATABASE QuanLyBanSach
go
USE QuanLyBanSach
GO
CREATE TABLE KhachHang(
MaKH INT PRIMARY KEY,
TenKH NVARCHAR(50) ,
TaiKhoan VARCHAR(50),
MatKhau VARCHAR(50),
Email VARCHAR(50),
GioiTinh NVARCHAR(5) CHECK (GioiTinh IN (N'Nam',N'Nữ')),
SDT VARCHAR(15),
NgaySinh DATE 
)
go
CREATE TABLE ChuDe(
MaChuDe INT PRIMARY KEY,
TenChuDe NVARCHAR(50)
)
go
CREATE TABLE NhaXuatBan(
MaNXB INT PRIMARY KEY,
TenNXB NVARCHAR(50),
DiaChi NVARCHAR(200),
SDT VARCHAR(15)
)
go
CREATE TABLE TacGia (
MaTG INT PRIMARY KEY,
TenTG NVARCHAR(50),
DiaChi NVARCHAR(200),
TieuSu NVARCHAR(MaX),
SDT VARCHAR(15)
)
go
CREATE TABLE Sach(
MaSach INT PRIMARY KEY,
TenSach NVARCHAR(50),
GiaBan DECIMAL(18,0),
MoTa NVARCHAR(MAX),
AnhBia NVARCHAR(50),
NgayCapNhat DATE,
SoLuongTon INT,
MaNXB INT REFERENCES dbo.NhaXuatBan(MaNXB),
MaChuDe INT REFERENCES dbo.ChuDe(MaChuDe) 
)
go
CREATE TABLE ChiTietTacGia (
MaTG INT REFERENCES dbo.TacGia(MaTG),
MaSach INT REFERENCES dbo.Sach(MaSach),
VaiTro NVARCHAR(50) ,
ViTri NVARCHAR(50),
PRIMARY KEY (MaTG,MaSach)
)
go
CREATE TABLE DonHang(
MaDH INT PRIMARY KEY,
DaThanhToan INT,
TinhTrangDH INT,
NgayDat DATE,
NgayGiao DATE,
MaKH INT REFERENCES dbo.KhachHang(MaKH)
)
go
CREATE TABLE ChiTietDonHang(
MaDH INT REFERENCES dbo.DonHang(MaDH),
MaSach INT REFERENCES dbo.Sach(MaSach),
SoLuong INT,
DonGia INT, 
PRIMARY KEY (MaDH,MaSach)
)
go